export interface Surah {
    number: number;
    name: string;
    arabicName: string;
    urduName: string;
    verses: number;
  }
  
  export const SURAHS: Surah[] = [
    { number: 1, name: "Al-Fatihah", arabicName: "الفاتحة", urduName: "الفاتحہ", verses: 7 },
    { number: 2, name: "Al-Baqarah", arabicName: "البقرة", urduName: "البقرہ", verses: 286 },
    { number: 3, name: "Aal-E-Imran", arabicName: "آل عمران", urduName: "آل عمران", verses: 200 },
    { number: 4, name: "An-Nisa", arabicName: "النساء", urduName: "النساء", verses: 176 },
    { number: 5, name: "Al-Ma'idah", arabicName: "المائدة", urduName: "المائدہ", verses: 120 },
    { number: 6, name: "Al-An'am", arabicName: "الأنعام", urduName: "الانعام", verses: 165 },
    { number: 7, name: "Al-A'raf", arabicName: "الأعراف", urduName: "الاعراف", verses: 206 },
    { number: 8, name: "Al-Anfal", arabicName: "الأنفال", urduName: "الانفال", verses: 75 },
    { number: 9, name: "At-Tawbah", arabicName: "التوبة", urduName: "التوبہ", verses: 129 },
    { number: 10, name: "Yunus", arabicName: "يونس", urduName: "یونس", verses: 109 },
    { number: 11, name: "Hud", arabicName: "هود", urduName: "ہود", verses: 123 },
    { number: 12, name: "Yusuf", arabicName: "يوسف", urduName: "یوسف", verses: 111 },
    { number: 13, name: "Ar-Ra'd", arabicName: "الرعد", urduName: "الرعد", verses: 43 },
    { number: 14, name: "Ibrahim", arabicName: "ابراهيم", urduName: "ابراہیم", verses: 52 },
    { number: 15, name: "Al-Hijr", arabicName: "الحجر", urduName: "الحجر", verses: 99 },
    { number: 16, name: "An-Nahl", arabicName: "النحل", urduName: "النحل", verses: 128 },
    { number: 17, name: "Al-Isra", arabicName: "الإسراء", urduName: "الاسراء", verses: 111 },
    { number: 18, name: "Al-Kahf", arabicName: "الكهف", urduName: "الکہف", verses: 110 },
    { number: 19, name: "Maryam", arabicName: "مريم", urduName: "مریم", verses: 98 },
    { number: 20, name: "Ta-Ha", arabicName: "طه", urduName: "طہ", verses: 135 },
    { number: 21, name: "Al-Anbiya", arabicName: "الأنبياء", urduName: "الانبیاء", verses: 112 },
    { number: 22, name: "Al-Hajj", arabicName: "الحج", urduName: "الحج", verses: 78 },
    { number: 23, name: "Al-Mu'minun", arabicName: "المؤمنون", urduName: "المؤمنون", verses: 118 },
    { number: 24, name: "An-Nur", arabicName: "النور", urduName: "النور", verses: 64 },
    { number: 25, name: "Al-Furqan", arabicName: "الفرقان", urduName: "الفرقان", verses: 77 },
    { number: 26, name: "Ash-Shu'ara", arabicName: "الشعراء", urduName: "الشعراء", verses: 227 },
    { number: 27, name: "An-Naml", arabicName: "النمل", urduName: "النمل", verses: 93 },
    { number: 28, name: "Al-Qasas", arabicName: "القصص", urduName: "القصص", verses: 88 },
    { number: 29, name: "Al-Ankabut", arabicName: "العنكبوت", urduName: "العنکبوت", verses: 69 },
    { number: 30, name: "Ar-Rum", arabicName: "الروم", urduName: "الروم", verses: 60 },
    { number: 31, name: "Luqman", arabicName: "لقمان", urduName: "لقمان", verses: 34 },
    { number: 32, name: "As-Sajdah", arabicName: "السجدة", urduName: "السجدہ", verses: 30 },
    { number: 33, name: "Al-Ahzab", arabicName: "الأحزاب", urduName: "الاحزاب", verses: 73 },
    { number: 34, name: "Saba", arabicName: "سبأ", urduName: "سبا", verses: 54 },
    { number: 35, name: "Fatir", arabicName: "فاطر", urduName: "فاطر", verses: 45 },
    { number: 36, name: "Ya-Sin", arabicName: "يس", urduName: "یٰسین", verses: 83 },
    { number: 37, name: "As-Saffat", arabicName: "الصافات", urduName: "الصافات", verses: 182 },
    { number: 38, name: "Sad", arabicName: "ص", urduName: "ص", verses: 88 },
    { number: 39, name: "Az-Zumar", arabicName: "الزمر", urduName: "الزمر", verses: 75 },
    { number: 40, name: "Ghafir", arabicName: "غافر", urduName: "غافر", verses: 85 },
    { number: 41, name: "Fussilat", arabicName: "فصلت", urduName: "فصلت", verses: 54 },
    { number: 42, name: "Ash-Shura", arabicName: "الشورى", urduName: "الشوریٰ", verses: 53 },
    { number: 43, name: "Az-Zukhruf", arabicName: "الزخرف", urduName: "الزخرف", verses: 89 },
    { number: 44, name: "Ad-Dukhan", arabicName: "الدخان", urduName: "الدخان", verses: 59 },
    { number: 45, name: "Al-Jathiyah", arabicName: "الجاثية", urduName: "الجاثیہ", verses: 37 },
    { number: 46, name: "Al-Ahqaf", arabicName: "الأحقاف", urduName: "الاحقاف", verses: 35 },
    { number: 47, name: "Muhammad", arabicName: "محمد", urduName: "محمد", verses: 38 },
    { number: 48, name: "Al-Fath", arabicName: "الفتح", urduName: "الفتح", verses: 29 },
    { number: 49, name: "Al-Hujurat", arabicName: "الحجرات", urduName: "الحجرات", verses: 18 },
    { number: 50, name: "Qaf", arabicName: "ق", urduName: "ق", verses: 45 },
    { number: 51, name: "Adh-Dhariyat", arabicName: "الذاريات", urduName: "الذاریات", verses: 60 },
    { number: 52, name: "At-Tur", arabicName: "الطور", urduName: "الطور", verses: 49 },
    { number: 53, name: "An-Najm", arabicName: "النجم", urduName: "النجم", verses: 62 },
    { number: 54, name: "Al-Qamar", arabicName: "القمر", urduName: "القمر", verses: 55 },
    { number: 55, name: "Ar-Rahman", arabicName: "الرحمن", urduName: "الرحمن", verses: 78 },
    { number: 56, name: "Al-Waqi'ah", arabicName: "الواقعة", urduName: "الواقعہ", verses: 96 },
    { number: 57, name: "Al-Hadid", arabicName: "الحديد", urduName: "الحدید", verses: 29 },
    { number: 58, name: "Al-Mujadila", arabicName: "المجادلة", urduName: "المجادلہ", verses: 22 },
    { number: 59, name: "Al-Hashr", arabicName: "الحشر", urduName: "الحشر", verses: 24 },
    { number: 60, name: "Al-Mumtahanah", arabicName: "الممتحنة", urduName: "الممتحنہ", verses: 13 },
    { number: 61, name: "As-Saf", arabicName: "الصف", urduName: "الصف", verses: 14 },
    { number: 62, name: "Al-Jumu'ah", arabicName: "الجمعة", urduName: "الجمعہ", verses: 11 },
    { number: 63, name: "Al-Munafiqun", arabicName: "المنافقون", urduName: "المنافقون", verses: 11 },
    { number: 64, name: "At-Taghabun", arabicName: "التغابن", urduName: "التغابن", verses: 18 },
    { number: 65, name: "At-Talaq", arabicName: "الطلاق", urduName: "الطلاق", verses: 12 },
    { number: 66, name: "At-Tahrim", arabicName: "التحريم", urduName: "التحریم", verses: 12 },
    { number: 67, name: "Al-Mulk", arabicName: "الملك", urduName: "الملک", verses: 30 },
    { number: 68, name: "Al-Qalam", arabicName: "القلم", urduName: "القلم", verses: 52 },
    { number: 69, name: "Al-Haqqah", arabicName: "الحاقة", urduName: "الحاقہ", verses: 52 },
    { number: 70, name: "Al-Ma'arij", arabicName: "المعارج", urduName: "المعارج", verses: 44 },
    { number: 71, name: "Nuh", arabicName: "نوح", urduName: "نوح", verses: 28 },
    { number: 72, name: "Al-Jinn", arabicName: "الجن", urduName: "الجن", verses: 28 },
    { number: 73, name: "Al-Muzzammil", arabicName: "المزمل", urduName: "المزمل", verses: 20 },
    { number: 74, name: "Al-Muddaththir", arabicName: "المدثر", urduName: "المدثر", verses: 56 },
    { number: 75, name: "Al-Qiyamah", arabicName: "القيامة", urduName: "القیامہ", verses: 40 },
    { number: 76, name: "Al-Insan", arabicName: "الانسان", urduName: "الانسان", verses: 31 },
    { number: 77, name: "Al-Mursalat", arabicName: "المرسلات", urduName: "المرسلات", verses: 50 },
    { number: 78, name: "An-Naba", arabicName: "النبأ", urduName: "النبا", verses: 40 },
    { number: 79, name: "An-Nazi'at", arabicName: "النازعات", urduName: "النازعات", verses: 46 },
    { number: 80, name: "Abasa", arabicName: "عبس", urduName: "عبس", verses: 42 },
    { number: 81, name: "At-Takwir", arabicName: "التكوير", urduName: "التکویر", verses: 29 },
    { number: 82, name: "Al-Infitar", arabicName: "الإنفطار", urduName: "الانفطار", verses: 19 },
    { number: 83, name: "Al-Mutaffifin", arabicName: "المطففين", urduName: "المطففین", verses: 36 },
    { number: 84, name: "Al-Inshiqaq", arabicName: "الإنشقاق", urduName: "الانشقاق", verses: 25 },
    { number: 85, name: "Al-Buruj", arabicName: "البروج", urduName: "البروج", verses: 22 },
    { number: 86, name: "At-Tariq", arabicName: "الطارق", urduName: "الطارق", verses: 17 },
    { number: 87, name: "Al-A'la", arabicName: "الأعلى", urduName: "الاعلیٰ", verses: 19 },
    { number: 88, name: "Al-Ghashiyah", arabicName: "الغاشية", urduName: "الغاشیہ", verses: 26 },
    { number: 89, name: "Al-Fajr", arabicName: "الفجر", urduName: "الفجر", verses: 30 },
    { number: 90, name: "Al-Balad", arabicName: "البلد", urduName: "البلد", verses: 20 },
    { number: 91, name: "Ash-Shams", arabicName: "الشمس", urduName: "الشمس", verses: 15 },
    { number: 92, name: "Al-Layl", arabicName: "الليل", urduName: "اللیل", verses: 21 },
    { number: 93, name: "Ad-Duha", arabicName: "الضحى", urduName: "الضحیٰ", verses: 11 },
    { number: 94, name: "Ash-Sharh", arabicName: "الشرح", urduName: "الشرح", verses: 8 },
    { number: 95, name: "At-Tin", arabicName: "التين", urduName: "التین", verses: 8 },
    { number: 96, name: "Al-Alaq", arabicName: "العلق", urduName: "العلق", verses: 19 },
    { number: 97, name: "Al-Qadr", arabicName: "القدر", urduName: "القدر", verses: 5 },
    { number: 98, name: "Al-Bayyinah", arabicName: "البينة", urduName: "البینہ", verses: 8 },
    { number: 99, name: "Az-Zalzalah", arabicName: "الزلزلة", urduName: "الزلزلہ", verses: 8 },
    { number: 100, name: "Al-Adiyat", arabicName: "العاديات", urduName: "العادیات", verses: 11 },
    { number: 101, name: "Al-Qari'ah", arabicName: "القارعة", urduName: "القارعہ", verses: 11 },
    { number: 102, name: "At-Takathur", arabicName: "التكاثر", urduName: "التکاثر", verses: 8 },
    { number: 103, name: "Al-Asr", arabicName: "العصر", urduName: "العصر", verses: 3 },
    { number: 104, name: "Al-Humazah", arabicName: "الهمزة", urduName: "الہمزہ", verses: 9 },
    { number: 105, name: "Al-Fil", arabicName: "الفيل", urduName: "الفیل", verses: 5 },
    { number: 106, name: "Quraysh", arabicName: "قريش", urduName: "قریش", verses: 4 },
    { number: 107, name: "Al-Ma'un", arabicName: "الماعون", urduName: "الماعون", verses: 7 },
    { number: 108, name: "Al-Kawthar", arabicName: "الكوثر", urduName: "الکوثر", verses: 3 },
    { number: 109, name: "Al-Kafirun", arabicName: "الكافرون", urduName: "الکافرون", verses: 6 },
    { number: 110, name: "An-Nasr", arabicName: "النصر", urduName: "النصر", verses: 3 },
    { number: 111, name: "Al-Masad", arabicName: "المسد", urduName: "المسد", verses: 5 },
    { number: 112, name: "Al-Ikhlas", arabicName: "الإخلاص", urduName: "الاخلاص", verses: 4 },
    { number: 113, name: "Al-Falaq", arabicName: "الفلق", urduName: "الفلق", verses: 5 },
    { number: 114, name: "An-Nas", arabicName: "الناس", urduName: "الناس", verses: 6 },
  ];
  