/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/admin-dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/attendance`; params?: Router.UnknownInputParams; } | { pathname: `/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/new-password`; params?: Router.UnknownInputParams; } | { pathname: `/phone-auth`; params?: Router.UnknownInputParams; } | { pathname: `/register-masjid`; params?: Router.UnknownInputParams; } | { pathname: `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/student-dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/verification`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/activity` | `/activity`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/class-selection` | `/class-selection`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/homework` | `/homework`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/admin-dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/attendance`; params?: Router.UnknownOutputParams; } | { pathname: `/forgot-password`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/new-password`; params?: Router.UnknownOutputParams; } | { pathname: `/phone-auth`; params?: Router.UnknownOutputParams; } | { pathname: `/register-masjid`; params?: Router.UnknownOutputParams; } | { pathname: `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `/student-dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/verification`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/activity` | `/activity`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/class-selection` | `/class-selection`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/homework` | `/homework`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/admin-dashboard${`?${string}` | `#${string}` | ''}` | `/attendance${`?${string}` | `#${string}` | ''}` | `/forgot-password${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/new-password${`?${string}` | `#${string}` | ''}` | `/phone-auth${`?${string}` | `#${string}` | ''}` | `/register-masjid${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `/student-dashboard${`?${string}` | `#${string}` | ''}` | `/verification${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/activity${`?${string}` | `#${string}` | ''}` | `/activity${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/class-selection${`?${string}` | `#${string}` | ''}` | `/class-selection${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/homework${`?${string}` | `#${string}` | ''}` | `/homework${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/admin-dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/attendance`; params?: Router.UnknownInputParams; } | { pathname: `/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/new-password`; params?: Router.UnknownInputParams; } | { pathname: `/phone-auth`; params?: Router.UnknownInputParams; } | { pathname: `/register-masjid`; params?: Router.UnknownInputParams; } | { pathname: `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/student-dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/verification`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/activity` | `/activity`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/class-selection` | `/class-selection`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/homework` | `/homework`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
